package service

import "time"

const storeVersion = 1

const storeNotice = "DO NOT EDIT THIS FILE MANUALLY. Use `shipyard service` to create, update, or delete services."

type Store struct {
	Notice   string          `json:"notice"`
	Version  int             `json:"version"`
	Services []ServiceRecord `json:"services"`
}

type ServiceRecord struct {
	ID          string            `json:"id"`
	Name        string            `json:"name"`
	Description string            `json:"description,omitempty"`
	Command     string            `json:"command"`
	WorkingDir  string            `json:"workingDir,omitempty"`
	Environment map[string]string `json:"environment,omitempty"`
	AutoRestart bool              `json:"autoRestart"`
	Enabled     bool              `json:"enabled"`
	CreatedAt   time.Time         `json:"createdAt"`
	UpdatedAt   time.Time         `json:"updatedAt"`
}

type ServiceInput struct {
	Name        *string            `json:"name"`
	Description *string            `json:"description"`
	Command     *string            `json:"command"`
	WorkingDir  *string            `json:"workingDir"`
	Environment *map[string]string `json:"environment"`
	AutoRestart *bool              `json:"autoRestart"`
	Enabled     *bool              `json:"enabled"`
}

type Platform string

const (
	PlatformSystemd Platform = "systemd"
	PlatformLaunchd Platform = "launchd"
)

type RuntimeStatus struct {
	State     string `json:"state"`
	SubState  string `json:"subState"`
	PID       int    `json:"pid"`
	EnabledAt string `json:"enabledAt"`
	SinceHint string `json:"sinceHint"`
	LastExit  int    `json:"lastExit"`
	Raw       string `json:"raw"`
}
