package fairway

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

// storeNotice is written as the first field of every saved routes.json to
// discourage manual edits.
const storeNotice = "DO NOT EDIT THIS FILE MANUALLY. Use 'shipyard fairway route' commands to manage routes."

// persistedConfig is the on-disk representation of Config. It adds a Notice
// field that is always written at the top for human readers. It is never
// exposed outside this file.
type persistedConfig struct {
	Notice        string  `json:"notice"`
	SchemaVersion string  `json:"schemaVersion"`
	Port          int     `json:"port"`
	Bind          string  `json:"bind"`
	MaxInFlight   int     `json:"maxInFlight,omitempty"`
	Routes        []Route `json:"routes"`
}

func toPersistedConfig(c Config) persistedConfig {
	return persistedConfig{
		Notice:        storeNotice,
		SchemaVersion: c.SchemaVersion,
		Port:          c.Port,
		Bind:          c.Bind,
		MaxInFlight:   c.MaxInFlight,
		Routes:        c.Routes,
	}
}

func fromPersistedConfig(p persistedConfig) Config {
	return Config{
		SchemaVersion: p.SchemaVersion,
		Port:          p.Port,
		Bind:          p.Bind,
		MaxInFlight:   p.MaxInFlight,
		Routes:        p.Routes,
	}
}

// defaultConfig returns a valid empty Config ready to use when no file exists.
func defaultConfig() Config {
	return Config{
		SchemaVersion: SchemaVersion,
		Port:          DefaultPort,
		Bind:          DefaultBind,
		Routes:        []Route{},
	}
}

// Repository is the persistence layer for the fairway daemon configuration.
type Repository interface {
	// Load reads Config from disk. If the file does not exist, it returns a
	// valid default Config without creating any file.
	Load() (Config, error)

	// Save atomically writes Config to disk, creating directories as needed.
	Save(Config) error

	// Path returns the absolute path of the underlying config file.
	Path() string
}

// FileRepository is a Repository backed by a JSON file on the local filesystem.
type FileRepository struct {
	path string
}

// NewFileRepository creates a FileRepository using DefaultConfigPath.
func NewFileRepository() (*FileRepository, error) {
	p, err := DefaultConfigPath()
	if err != nil {
		return nil, fmt.Errorf("resolve config path: %w", err)
	}
	return &FileRepository{path: p}, nil
}

// NewFileRepositoryAt creates a FileRepository using an explicit path.
// Useful for testing and for CLI overrides via --config flag.
func NewFileRepositoryAt(path string) *FileRepository {
	return &FileRepository{path: path}
}

// Path returns the absolute path to the routes.json file.
func (r *FileRepository) Path() string {
	return r.path
}

// Load reads and validates the config file. If the file does not exist it
// returns a default Config without touching the filesystem.
func (r *FileRepository) Load() (Config, error) {
	data, err := os.ReadFile(r.path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return defaultConfig(), nil
		}
		return Config{}, fmt.Errorf("read %s: %w", r.path, err)
	}

	var p persistedConfig
	if err := json.Unmarshal(data, &p); err != nil {
		return Config{}, fmt.Errorf("parse %s: %w", r.path, err)
	}

	cfg := fromPersistedConfig(p)

	if err := cfg.Validate(); err != nil {
		return Config{}, fmt.Errorf("invalid routes.json: %w", err)
	}

	return cfg, nil
}

// Save validates cfg, then atomically writes it to disk using a temp-file +
// rename strategy. The directory is created (mode 0700) if it does not exist.
// The final file has mode 0600.
func (r *FileRepository) Save(cfg Config) error {
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("refusing to save invalid config: %w", err)
	}

	dir := filepath.Dir(r.path)
	if err := os.MkdirAll(dir, 0700); err != nil {
		return fmt.Errorf("create dir %s: %w", dir, err)
	}

	data, err := json.MarshalIndent(toPersistedConfig(cfg), "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config: %w", err)
	}
	// Append trailing newline for POSIX compliance.
	data = append(data, '\n')

	// Write to a temp file in the same directory so that os.Rename is atomic
	// (same filesystem / mount point).
	tmp, err := os.CreateTemp(dir, "routes.*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file in %s: %w", dir, err)
	}
	tmpPath := tmp.Name()

	// Best-effort cleanup of the temp file on any error path.
	var committed bool
	defer func() {
		if !committed {
			_ = os.Remove(tmpPath)
		}
	}()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("write temp file %s: %w", tmpPath, err)
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("sync temp file %s: %w", tmpPath, err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close temp file %s: %w", tmpPath, err)
	}

	// Set mode 0600 on the temp file before renaming so the final file has
	// the correct permissions (rename preserves the mode on most OSes).
	if err := os.Chmod(tmpPath, 0600); err != nil {
		return fmt.Errorf("chmod temp file %s: %w", tmpPath, err)
	}

	if err := os.Rename(tmpPath, r.path); err != nil {
		return fmt.Errorf("rename %s → %s: %w", tmpPath, r.path, err)
	}

	committed = true
	return nil
}

// DefaultConfigPath returns the path to routes.json, respecting the
// SHIPYARD_HOME environment variable if set.
func DefaultConfigPath() (string, error) {
	if home := os.Getenv("SHIPYARD_HOME"); home != "" {
		return filepath.Join(home, "fairway", "routes.json"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home dir: %w", err)
	}
	return filepath.Join(home, ".shipyard", "fairway", "routes.json"), nil
}
