package fairway

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
)

const storeNotice = "DO NOT EDIT THIS FILE MANUALLY. Use 'shipyard fairway route' commands to manage routes."

// Repository loads and persists Fairway route configuration.
type Repository interface {
	Load() (Config, error)
	Save(Config) error
	Path() string
}

// FileRepository stores Fairway route configuration in a single JSON file.
type FileRepository struct {
	path string

	beforeRename func(tempPath, finalPath string) error
}

type persistedConfig struct {
	Notice        string  `json:"notice"`
	SchemaVersion string  `json:"schemaVersion"`
	Port          int     `json:"port"`
	Bind          string  `json:"bind"`
	MaxInFlight   int     `json:"maxInFlight,omitempty"`
	Routes        []Route `json:"routes"`
}

// NewFileRepository constructs a repository at the default Fairway config path.
func NewFileRepository() (*FileRepository, error) {
	path, err := DefaultConfigPath()
	if err != nil {
		return nil, err
	}
	return NewFileRepositoryAt(path), nil
}

// NewFileRepositoryAt constructs a repository for the provided path.
func NewFileRepositoryAt(path string) *FileRepository {
	if absPath, err := filepath.Abs(path); err == nil {
		path = absPath
	}
	return &FileRepository{path: path}
}

// DefaultConfigPath returns the default routes.json location for the current user.
func DefaultConfigPath() (string, error) {
	if shipyardHome := os.Getenv("SHIPYARD_HOME"); shipyardHome != "" {
		return filepath.Join(shipyardHome, "fairway", "routes.json"), nil
	}

	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve user home dir: %w", err)
	}
	return filepath.Join(homeDir, ".shipyard", "fairway", "routes.json"), nil
}

// Path returns the repository file path.
func (r *FileRepository) Path() string {
	return r.path
}

// Load reads and validates the persisted Fairway config. Missing files return defaults.
func (r *FileRepository) Load() (Config, error) {
	data, err := os.ReadFile(r.path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return Config{
				SchemaVersion: SchemaVersion,
				Port:          DefaultPort,
				Bind:          DefaultBind,
				Routes:        []Route{},
			}, nil
		}
		return Config{}, fmt.Errorf("read routes config %s: %w", r.path, err)
	}

	var persisted persistedConfig
	if err := json.Unmarshal(data, &persisted); err != nil {
		return Config{}, fmt.Errorf("read routes config %s: invalid json: %w", r.path, err)
	}

	cfg := persisted.toConfig()
	if err := cfg.Validate(); err != nil {
		return Config{}, fmt.Errorf("invalid routes.json %s: %w", r.path, err)
	}

	if cfg.Routes == nil {
		cfg.Routes = []Route{}
	}

	return cfg, nil
}

// Save validates and atomically persists the Fairway config to disk.
func (r *FileRepository) Save(cfg Config) (err error) {
	if err := cfg.Validate(); err != nil {
		return fmt.Errorf("validate config for %s: %w", r.path, err)
	}

	persisted := persistedConfig{
		Notice:        storeNotice,
		SchemaVersion: cfg.SchemaVersion,
		Port:          cfg.Port,
		Bind:          cfg.Bind,
		MaxInFlight:   cfg.MaxInFlight,
		Routes:        cfg.Routes,
	}

	data, err := json.MarshalIndent(persisted, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal config for %s: %w", r.path, err)
	}
	data = append(data, '\n')

	dir := filepath.Dir(r.path)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create config dir %s: %w", dir, err)
	}
	if err := os.Chmod(dir, 0o700); err != nil {
		return fmt.Errorf("chmod config dir %s: %w", dir, err)
	}

	tempFile, err := os.CreateTemp(dir, "routes.*.tmp")
	if err != nil {
		return fmt.Errorf("create temp file in %s: %w", dir, err)
	}

	tempPath := tempFile.Name()
	defer func() {
		if err != nil {
			_ = os.Remove(tempPath)
		}
	}()

	if err = tempFile.Chmod(0o600); err != nil {
		_ = tempFile.Close()
		return fmt.Errorf("chmod temp file %s: %w", tempPath, err)
	}
	if _, err = tempFile.Write(data); err != nil {
		_ = tempFile.Close()
		return fmt.Errorf("write temp file %s: %w", tempPath, err)
	}
	if err = tempFile.Sync(); err != nil {
		_ = tempFile.Close()
		return fmt.Errorf("sync temp file %s: %w", tempPath, err)
	}
	if err = tempFile.Close(); err != nil {
		return fmt.Errorf("close temp file %s: %w", tempPath, err)
	}

	if r.beforeRename != nil {
		if err = r.beforeRename(tempPath, r.path); err != nil {
			return fmt.Errorf("before rename for %s: %w", r.path, err)
		}
	}

	if err = os.Rename(tempPath, r.path); err != nil {
		return fmt.Errorf("rename temp file %s to %s: %w", tempPath, r.path, err)
	}
	if err = os.Chmod(r.path, 0o600); err != nil {
		return fmt.Errorf("chmod config file %s: %w", r.path, err)
	}

	return nil
}

func (p persistedConfig) toConfig() Config {
	return Config{
		SchemaVersion: p.SchemaVersion,
		Port:          p.Port,
		Bind:          p.Bind,
		MaxInFlight:   p.MaxInFlight,
		Routes:        p.Routes,
	}
}
